version: "3"
services:
  
  frontend:
   build:
      context: ./frontend
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: mern-frontend
   networks:
    -  mern-stack-net
   volumes:
    -  ./frontend:/usr/apps
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
      - 3080:3080
   container_name: mern-backend
   environment:
      PORT: 3080
   networks:
     - mern-stack-net
   volumes:
    - ./backend:/usr/app
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local